spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    org.springframework: warn
    org.hibernate: warn

sentry:
  dsn: ${SENTRY_DSN}
  environment: prod
  send-default-pii: false