spring:
  profiles:
    active: ${PROFILE:dev}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:muzusi}?rewriteBatchedStatements=true
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASS:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      authentication-database: ${MONGODB_AUTH_DB:admin}
      database: ${MONGODB_DATABASE:test}
      username: ${MONGODB_USERNAME:root}
      password: ${MONGODB_PASSWORD:password}

jwt:
  secret: ${JWT_KEY:exampleSecretKeyForMuzusiSystemAccessSecretKeyTestForPadding}
  access-expiration: ${JWT_ACCESS_EXPIRATION:1800000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}
  issuer: ${JWT_ISSUER:muzusi}

oauth2:
  kakao:
    tokenUri: https://kauth.kakao.com/oauth/token
    clientId: ${KAKAO_CLIENT_ID}
    clientSecret: ${KAKAO_CLIENT_SECRET}
    redirectUri: ${KAKAO_REDIRECT_URL}
    userInfoUri: https://kapi.kakao.com/v2/user/me

  naver:
    tokenUri: https://nid.naver.com/oauth2.0/token
    clientId: ${NAVER_CLIENT_ID}
    clientSecret: ${NAVER_CLIENT_SECRET}
    redirectUri: ${NAVER_REDIRECT_URL}
    userInfoUri: https://openapi.naver.com/v1/nid/me

api:
  checker:
    storage:
      filepath: ${user.home}/api-status.json

token:
  refresh:
    in-redis: ${REDIS_REFRESH_EXPIRATION:648000}

news:
  clientId: ${NEWS_CLIENT_ID}
  clientSecret: ${NEWS_CLIENT_SECRET}
  newsApiUrl: ${NEWS_API_URL}

kis:
  domain: ${KIS_DOMAIN:https://openapi.koreainvestment.com:9443}
  web-socket-domain: ${KIS_WEBSOCKET_DOMAIN:ws://ops.koreainvestment.com:21000}
  app-keys: ${KIS_APPKEYS}
  app-secrets: ${KIS_APPSECRETS}

data:
  stock-code-path: ${DATA_STOCK_CODE_PATH:data/stock/stock-code.csv}

webhook:
  discord:
    url: ${DISCORD_WEBHOOK_URL:https://discord.com/api/webhooks}