spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    org.springframework: warn
    org.hibernate: warn

webhook:
  discord:
    url: ${DISCORD_WEBHOOK_URL:https://discord.com/api/webhooks}